---
- name: SSH into instance
  shell: cat /etc/resolv.conf
  register: ssh_output

- name: Log ssh_output
  debug:
    var: ssh_output

# Add your own plays here
- name: Install mysql
  yum:
    name: mariadb-server
    state: present
- name: Install Python MySQL libraries
  yum: pkg=MySQL-python state=latest
- name: start mysql server and enable it on reboot
  service: 
    name: mariadb 
    state: started 
    enabled: true  
- name: update mysql root password for all root accounts
  mysql_user:
    name: root
    host: vmware_host
    password: "{{ mysql_root_password }}"
    login_user: root
    login_password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  #with_items: "{{ vmware_created_vms.results }}"
- name: Copy the root credentials as .my.cnf file
  #template: src=root.cnf.j2 dest=~/.my.cnf mode=0600
  blockinfile:
    path: ~/.my.cnf
    state: present
    create: true
    block: |
      [client]
      user = root
      password = "{{ mysql_root_password }}"
- name: Create a New Test DB 
  mysql_db: 
    name: "{{ database_name }}"
    state: present 
    login_user: root 
    login_password: "{{ mysql_root_password }}"
